# Generated by Django 5.2 on 2026-05-20 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0024_assigment_imprime_fields'),
        ('masterdata', '0018_alter_stock_unit_of_measure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('app_version', models.CharField(blank=True, max_length=20, null=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pda_devices', to='inventory.inventory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pda_devices', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pda_devices', to='masterdata.warehouse')),
            ],
            options={
                'verbose_name': 'Terminal PDA',
                'verbose_name_plural': 'Terminaux PDA',
                'indexes': [models.Index(fields=['-last_seen_at'], name='device_last_seen_idx'), models.Index(fields=['user'], name='device_user_idx')],
            },
        ),
    ]
