# Generated by Django 5.2 on 2025-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Internal_Product_Code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='Product_Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('OBSOLETE', 'OBSOLETE')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Internal_Product_Code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('OBSOLETE', 'OBSOLETE')]),
        ),
    ]
