# Generated by Django 5.2 on 2025-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Barcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Barcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Code-barres'),
        ),
    ]
