# Generated by Django 5.2 on 2025-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='dlc',
            field=models.BooleanField(default=False, verbose_name='DLC'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='n_lot',
            field=models.BooleanField(default=False, verbose_name='N° lot'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='n_serie',
            field=models.BooleanField(default=False, verbose_name='N° série'),
        ),
        migrations.AddField(
            model_name='product',
            name='dlc',
            field=models.BooleanField(default=False, verbose_name='DLC'),
        ),
        migrations.AddField(
            model_name='product',
            name='n_lot',
            field=models.BooleanField(default=False, verbose_name='N° lot'),
        ),
        migrations.AddField(
            model_name='product',
            name='n_serie',
            field=models.BooleanField(default=False, verbose_name='N° série'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='Is_Variant',
            field=models.BooleanField(default=False, verbose_name='variante'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Is_Variant',
            field=models.BooleanField(default=False, verbose_name='variante'),
        ),
    ]
