# Generated by Django 5.2 on 2025-07-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Internal_Product_Code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='Product_Group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Groupe de produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Internal_Product_Code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Groupe de produit'),
        ),
    ]
