# Generated by Django 5.2 on 2025-05-21 11:58

from django.db import migrations, models
import django.db.models.deletion

def set_default_inventory(apps, schema_editor):
    Stock = apps.get_model('masterdata', 'Stock')
    Inventory = apps.get_model('inventory', 'Inventory')
    
    # Créer un inventaire par défaut s'il n'existe pas
    default_inventory, created = Inventory.objects.get_or_create(
        reference='INV-DEFAULT',
        defaults={
            'label': 'Inventaire par défaut',
            'date': '2024-01-01',
            'status': 'CURRENT'
        }
    )
    
    # Mettre à jour tous les stocks existants
    Stock.objects.all().update(inventory=default_inventory)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='inventory',
            field=models.ForeignKey(
                'inventory.Inventory',
                on_delete=django.db.models.deletion.CASCADE,
                null=True
            ),
        ),
        migrations.RunPython(set_default_inventory),
        migrations.AlterField(
            model_name='stock',
            name='inventory',
            field=models.ForeignKey(
                'inventory.Inventory',
                on_delete=django.db.models.deletion.CASCADE
            ),
        ),
    ]
