# Generated by Django 5.2 on 2025-07-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_historicalproduct_internal_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Stock_Unit',
            field=models.CharField(max_length=30, verbose_name='Unité de stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Stock_Unit',
            field=models.CharField(max_length=30, verbose_name='Unité de stock'),
        ),
    ]
