# Generated by Django 5.2 on 2025-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_historicalproduct_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Internal_Product_Code',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Internal_Product_Code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code produit'),
        ),
    ]
