# Generated by Django 5.2 on 2025-11-13 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_historicalproduct_internal_product_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('validated_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VALIDATING', 'Validation en cours'), ('PROCESSING', 'Import en cours'), ('COMPLETED', 'Terminé avec succès'), ('CANCELLED', 'Annulé (erreurs détectées)'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('errors_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Tâche d'import",
                'verbose_name_plural': "Tâches d'import",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('row_number', models.IntegerField(verbose_name='Numéro de ligne')),
                ('error_type', models.CharField(max_length=100, verbose_name="Type d'erreur")),
                ('error_message', models.TextField(verbose_name="Message d'erreur")),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Champ concerné')),
                ('field_value', models.TextField(blank=True, null=True, verbose_name='Valeur du champ')),
                ('row_data', models.JSONField(default=dict, verbose_name='Données de la ligne')),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='masterdata.importtask')),
            ],
            options={
                'verbose_name': "Erreur d'import",
                'verbose_name_plural': "Erreurs d'import",
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['import_task', 'row_number'], name='masterdata__import__e6f9e3_idx')],
            },
        ),
    ]
