# Generated by Django 5.2 on 2025-07-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegroupementEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regroupement_emplacement', to='masterdata.account')),
            ],
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='regroupement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.regroupementemplacement'),
        ),
        migrations.AddField(
            model_name='location',
            name='regroupement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='masterdata.regroupementemplacement'),
        ),
    ]
