# Generated by Django 5.2 on 2025-11-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_importtask_importerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Short_Description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Short_Description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Désignation'),
        ),
    ]
