# Generated by Django 5.2 on 2025-08-08 13:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_regroupementemplacement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNSerie',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(db_index=True, max_length=20, verbose_name='Référence')),
                ('n_serie', models.CharField(db_index=True, max_length=100, verbose_name='Numéro de série')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('USED', 'Utilisé'), ('EXPIRED', 'Expiré'), ('BLOCKED', 'Bloqué')], default='ACTIVE', verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_fabrication', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de garantie')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'historical Numéro de série',
                'verbose_name_plural': 'historical Numéros de série',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('n_serie', models.CharField(max_length=100, unique=True, verbose_name='Numéro de série')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('USED', 'Utilisé'), ('EXPIRED', 'Expiré'), ('BLOCKED', 'Bloqué')], default='ACTIVE', verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_fabrication', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin de garantie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_serie', to='masterdata.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Numéro de série',
                'verbose_name_plural': 'Numéros de série',
                'indexes': [models.Index(fields=['n_serie'], name='masterdata__n_serie_94ddb1_idx'), models.Index(fields=['product', 'status'], name='masterdata__product_6e218a_idx')],
                'unique_together': {('n_serie', 'product')},
            },
        ),
    ]
