# Generated by Django 5.2 on 2025-06-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_add_type_ressource_to_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalressource',
            name='type_ressource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.typeressource', verbose_name='Type de ressource'),
        ),
    ]
