# Generated by Django 5.2 on 2025-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_make_barcode_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Product_Status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('OBSOLETE', 'Obsolète')], default='ACTIVE', verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('OBSOLETE', 'Obsolète')], default='ACTIVE', verbose_name='Statut'),
        ),
    ]
