# Generated by Django 5.2 on 2025-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_alter_historicalproduct_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='location_reference',
            field=models.CharField(max_length=30, verbose_name="Référence de l'emplacement"),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_reference',
            field=models.CharField(max_length=30, verbose_name="Référence de l'emplacement"),
        ),
    ]
