# Generated by Django 5.2 on 2025-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_alter_historicallocation_location_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='Short_Description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Code-barres'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Short_Description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Désignation'),
        ),
    ]
