# Generated by Django 5.2 on 2025-11-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_alter_historicalproduct_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
