# Generated by Django 5.2 on 2025-12-13 13:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_assigment_termine_date_and_more'),
        ('masterdata', '0011_alter_historicallocation_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventoryLocationJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job', models.CharField(max_length=255, verbose_name='Job')),
                ('session_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session 1')),
                ('session_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session 2')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('emplacement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location', verbose_name='Emplacement')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inventaire', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': "historical Job d'inventaire par emplacement",
                'verbose_name_plural': "historical Jobs d'inventaire par emplacement",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryLocationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job', models.CharField(max_length=255, verbose_name='Job')),
                ('session_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session 1')),
                ('session_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Session 2')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_jobs', to='masterdata.location', verbose_name='Emplacement')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_jobs', to='inventory.inventory', verbose_name='Inventaire')),
            ],
            options={
                'verbose_name': "Job d'inventaire par emplacement",
                'verbose_name_plural': "Jobs d'inventaire par emplacement",
                'indexes': [models.Index(fields=['inventaire', 'emplacement'], name='masterdata__inventa_5977e9_idx'), models.Index(fields=['job'], name='masterdata__job_c466ad_idx')],
            },
        ),
    ]
