# Generated by Django 5.2 on 2025-12-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0012_historicalinventorylocationjob_inventorylocationjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorylocationjob',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='inventorylocationjob',
            name='job',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job'),
        ),
    ]
