# Generated by Django 5.2 on 2025-12-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_nom_historicalpersonne_full_name_and_more'),
        ('masterdata', '0013_alter_historicalinventorylocationjob_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='inventory.inventory', verbose_name='Inventaire'),
        ),
    ]
