# Generated by Django 5.2 on 2025-12-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_importtask_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='Internal_Product_Code',
            field=models.CharField(max_length=100, verbose_name='Code produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Internal_Product_Code',
            field=models.CharField(max_length=100, verbose_name='Code produit'),
        ),
    ]
