# Generated by Django 5.2 on 2026-01-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0015_alter_historicalproduct_internal_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regroupementemplacement',
            name='warehouse',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='regroupement_emplacement', to='masterdata.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='regroupementemplacement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regroupement_emplacement', to='masterdata.account'),
        ),
    ]
