# Generated by Django 5.2 on 2026-01-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_regroupementemplacement_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='masterdata.warehouse'),
            preserve_default=False,
        ),
    ]
