# Generated by Django 5.2 on 2026-03-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_historicalstock_warehouse_stock_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.unitofmeasure'),
        ),
    ]
