# Generated by Django 5.2 on 2026-07-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0018_alter_stock_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optionnel — extractions ERP article/quantité sans emplacement', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location', verbose_name='Emplacement'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Optionnel — extractions ERP article/quantité sans emplacement', null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.location', verbose_name='Emplacement'),
        ),
    ]
