# Generated by Django 5.2 on 2026-07-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_stock_location_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Renseigné pour les imports de stocks théoriques (multi-magasins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_tasks', to='masterdata.warehouse', verbose_name='Magasin'),
        ),
    ]
