# Generated by Django 6.0.6 on 2026-08-06 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_importtask_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='quantity_available',
            field=models.IntegerField(
                blank=True,
                help_text="Optionnel — vide si non renseignée à l'import (GENERAL)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity_available',
            field=models.IntegerField(
                blank=True,
                help_text="Optionnel — vide si non renseignée à l'import (GENERAL)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
