# Generated by Django 5.2 on 2025-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Supprimer le champ role du modèle UserApp
        migrations.RemoveField(
            model_name='userapp',
            name='role',
        ),
        # Supprimer le champ role du modèle historique
        migrations.RemoveField(
            model_name='historicaluserapp',
            name='role',
        ),
        # Ajouter le champ type avec une valeur par défaut
        migrations.AddField(
            model_name='userapp',
            name='type',
            field=models.CharField(
                choices=[('Web', 'Web'), ('Mobile', 'Mobile')],
                default='Web',
                max_length=100,
                verbose_name='Type'
            ),
        ),
        # Ajouter le champ type aux enregistrements historiques avec une valeur par défaut
        migrations.AddField(
            model_name='historicaluserapp',
            name='type',
            field=models.CharField(
                choices=[('Web', 'Web'), ('Mobile', 'Mobile')],
                default='Web',
                max_length=100,
                verbose_name='Type'
            ),
        ),
    ]
