# Generated by Django 5.2 on 2025-08-11 17:20

from django.db import migrations


def add_compte_id_to_historical_table(apps, schema_editor):
    """
    Ajoute la colonne compte_id à la table historique users_historicaluserapp
    """
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne existe déjà
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'users_historicaluserapp' 
            AND column_name = 'compte_id';
        """)
        
        if not cursor.fetchone():
            # Ajouter la colonne compte_id
            cursor.execute("""
                ALTER TABLE users_historicaluserapp 
                ADD COLUMN compte_id INTEGER;
            """)


def remove_compte_id_from_historical_table(apps, schema_editor):
    """
    Supprime la colonne compte_id de la table historique (opération inverse)
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE users_historicaluserapp 
            DROP COLUMN IF EXISTS compte_id;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('masterdata', '0001_initial'),  # S'assurer que la table account existe
    ]

    operations = [
        migrations.RunPython(
            add_compte_id_to_historical_table,
            remove_compte_id_from_historical_table,
        ),
    ]
