# Generated by Django 5.2 on 2025-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250628_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserapp',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=100, verbose_name='Type'),
        ),
    ]
