# Generated by Django 5.2 on 2025-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluserapp_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserapp',
            name='comptage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comptage'),
        ),
        migrations.AddField(
            model_name='userapp',
            name='comptage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Comptage'),
        ),
    ]
