# Generated by Django 5.2 on 2025-04-24 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcounting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventorydetail',
            name='counting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='historicalinventorydetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventorydetail',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='historicalinventorydetail',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='counting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='historicalpda',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpersonne',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.account'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalcounting',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='counting',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='counting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_1', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_2', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_3', to='inventory.inventorydetail'),
        ),
        migrations.AddField(
            model_name='job',
            name='counting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='job',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.job'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='pda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.pda'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='pda',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.pda'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_job_details', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='personne_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_job_details', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='personne',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='personne_two',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='planning',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='planning',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='setting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='masterdata.account'),
        ),
        migrations.AddField(
            model_name='setting',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='setting',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='masterdata.warehouse'),
        ),
    ]
