# Generated by Django 5.2 on 2025-07-16 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countingdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='countingdetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_1', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_2', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='ligne_comptage_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecart_ligne_3', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='counting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'Mobile'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcounting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcountingdetail',
            name='counting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='historicalcountingdetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcountingdetail',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='historicalcountingdetail',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventorydetailressource',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinventorydetailressource',
            name='ressource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.ressource'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='historicaljobdetailressource',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaljobdetailressource',
            name='ressource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.ressource'),
        ),
        migrations.AddField(
            model_name='historicalnserie',
            name='counting_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalnserie',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpersonne',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse', verbose_name='Entrepôt'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.account'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalplanning',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory', verbose_name='Inventaire'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalinventorydetailressource',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='historicalcounting',
            name='inventory',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventory', verbose_name='Inventaire'),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='counting',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countings', to='inventory.inventory', verbose_name='Inventaire'),
        ),
        migrations.AddField(
            model_name='inventorydetailressource',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventorydetailressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.ressource'),
        ),
        migrations.AddField(
            model_name='job',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='job',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.warehouse'),
        ),
        migrations.AddField(
            model_name='historicaljobdetailressource',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.job'),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.job'),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.job'),
        ),
        migrations.AddField(
            model_name='assigment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='jobdetailressource',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.job'),
        ),
        migrations.AddField(
            model_name='jobdetailressource',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.ressource'),
        ),
        migrations.AddField(
            model_name='nserie',
            name='counting_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='personne',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='personne_two',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='assigment',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_job_details', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='assigment',
            name='personne_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_job_details', to='inventory.personne'),
        ),
        migrations.AddField(
            model_name='planning',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Inventaire'),
        ),
        migrations.AddField(
            model_name='planning',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.warehouse', verbose_name='Entrepôt'),
        ),
        migrations.AddField(
            model_name='setting',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='masterdata.account'),
        ),
        migrations.AddField(
            model_name='setting',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='setting',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awi_links', to='masterdata.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='ecartcomptage',
            constraint=models.CheckConstraint(condition=models.Q(('ecart__isnull', True), ('ecart__gte', 0), _connector='OR'), name='ecart_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='ecartcomptage',
            constraint=models.CheckConstraint(condition=models.Q(('result__isnull', True), ('result__gte', 0), _connector='OR'), name='result_positive_or_null'),
        ),
    ]
