# Generated by Django 5.2 on 2025-07-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='pret_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pret_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE')], max_length=10),
        ),
    ]
