# Generated by Django 5.2 on 2025-07-13 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d\'affectation'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d\'entame'),
        ),
        migrations.AddField(
            model_name='job',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d\'affectation'),
        ),
        migrations.AddField(
            model_name='job',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date d\'entame'),
        ),
    ]
