# Generated by Django 5.2 on 2025-08-15 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalNSerie',
            new_name='HistoricalNSerieInventory',
        ),
        migrations.RenameModel(
            old_name='NSerie',
            new_name='NSerieInventory',
        ),
        migrations.AlterModelOptions(
            name='historicalnserieinventory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical n serie inventory', 'verbose_name_plural': 'historical n serie inventorys'},
        ),
    ]
