# Generated by Django 5.2 on 2025-06-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljob',
            old_name='invetory',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='invetory',
            new_name='inventory',
        ),
    ]
