# Generated by Django 5.2 on 2025-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventory',
            name='inventory_type',
            field=models.CharField(choices=[('TOURNANT', 'TOURNANT'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('TOURNANT', 'TOURNANT'), ('GENERAL', 'GENERAL')], default='GENERAL', max_length=20),
        ),
    ]
