# Generated by Django 5.2 on 2025-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_counting_quantity_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counting',
            name='status',
            field=models.CharField(choices=[('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('CLOTURE', 'CLOTURE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcounting',
            name='status',
            field=models.CharField(choices=[('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('CLOTURE', 'CLOTURE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='status',
            field=models.CharField(choices=[('EN PREPARATION', 'EN PREPARATION'), ('EN REALISATION', 'EN REALISATION'), ('TERMINE', 'TERMINE'), ('CLOTURE', 'CLOTURE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('EN PREPARATION', 'EN PREPARATION'), ('EN REALISATION', 'EN REALISATION'), ('TERMINE', 'TERMINE'), ('CLOTURE', 'CLOTURE')], max_length=50),
        ),
    ]
