# Generated by Django 5.2 on 2025-07-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicaljob_affecte_date_historicaljob_entame_date_and_more'),
    ]

    operations = [
    ]
