# Generated by Django 5.2 on 2025-06-29 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_countingdetail_dlc_countingdetail_n_lot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigment',
            options={'verbose_name': 'Affectation', 'verbose_name_plural': 'Affectations'},
        ),
        migrations.AlterModelOptions(
            name='historicalassigment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Affectation', 'verbose_name_plural': 'historical Affectations'},
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='affecte_date',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='date_estime',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='entame_date',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='pret_date',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='transfert_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='affecte_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_estime',
        ),
        migrations.RemoveField(
            model_name='job',
            name='entame_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pret_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='transfert_date',
        ),
        migrations.AddField(
            model_name='assigment',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigment',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigment',
            name='pret_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE')], default='EN ATTENTE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assigment',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='pret_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE')], default='EN ATTENTE', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='session',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Mobile'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalassigment',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type': 'Mobile'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE')], max_length=10),
        ),
    ]
