# Generated by Django 5.2 on 2025-08-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicaljob_affecte_date_historicaljob_entame_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobdetail',
            name='counting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.counting'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='counting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.counting'),
        ),
    ]
