# Generated by Django 5.2 on 2025-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_counting_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='current_status_date',
            new_name='cloture_status_date',
        ),
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='end_status_date',
            new_name='en_attente_status_date',
        ),
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='lunch_status_date',
            new_name='en_preparation_status_date',
        ),
        migrations.RenameField(
            model_name='historicalinventory',
            old_name='pending_status_date',
            new_name='en_realisation_status_date',
        ),
        migrations.RenameField(
            model_name='historicaljob',
            old_name='end_date',
            new_name='cloture_date',
        ),
        migrations.RenameField(
            model_name='historicaljob',
            old_name='lunch_date',
            new_name='date_estime',
        ),
        migrations.RenameField(
            model_name='historicaljob',
            old_name='start_date',
            new_name='entame_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='current_status_date',
            new_name='cloture_status_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='lunch_status_date',
            new_name='en_attente_status_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='end_status_date',
            new_name='en_preparation_status_date',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='pending_status_date',
            new_name='en_realisation_status_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='end_date',
            new_name='cloture_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='lunch_date',
            new_name='date_estime',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='start_date',
            new_name='entame_date',
        ),
        migrations.AddField(
            model_name='historicalinventory',
            name='ternime_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='lance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ternime_status_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='lance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='transfert_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counting',
            name='status',
            field=models.CharField(choices=[('LAUNCH', 'Launch'), ('START', 'Start'), ('END', 'End')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcounting',
            name='status',
            field=models.CharField(choices=[('LAUNCH', 'Launch'), ('START', 'Start'), ('END', 'End')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('EN PREPARATION', 'EN PREPARATION'), ('EN REALISATION', 'EN REALISATION'), ('TERMINE', 'TERMINE'), ('CLOTURE', 'CLOTURE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('LANCE', 'LANCE'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('CLOTURE', 'CLOTURE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('EN PREPARATION', 'EN PREPARATION'), ('EN REALISATION', 'EN REALISATION'), ('TERMINE', 'TERMINE'), ('CLOTURE', 'CLOTURE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('LANCE', 'LANCE'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('CLOTURE', 'CLOTURE')], max_length=10),
        ),
    ]
