# Generated by Django 5.2 on 2025-07-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_historicalinventory_inventory_type_and_more'),
        ('inventory', '0004_alter_assigment_options_and_more'),
    ]

    operations = [
    ]
