# Generated by Django 5.2 on 2025-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='saisie_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='en_attente_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='termine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='saisie_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='en_attente_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='termine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SAISIE MANUELLE', 'SAISIE MANUELLE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaljobdetail',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('TERMINE', 'TERMINE')], default='EN ATTENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SAISIE MANUELLE', 'SAISIE MANUELLE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('TERMINE', 'TERMINE')], default='EN ATTENTE', max_length=50),
        ),
    ]
