# Generated by Django 5.2 on 2025-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_current_status_date_historicalinventory_cloture_status_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorydetail',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='en_attente_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorydetail',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='en_attente_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
