# Generated by Django 5.2 on 2025-08-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_historicalnserie_historicalnserieinventory_and_more'),
        ('inventory', '0005_historicaljob_saisie_manuelle_date_and_more'),
    ]

    operations = [
    ]
