# Generated by Django 5.2 on 2025-10-29 13:44

import apps.inventory.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_merge_20250815_1400'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptageSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sequence_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ecart_with_previous', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['ecart_comptage', 'sequence_number'],
            },
            bases=(models.Model, apps.inventory.models.ReferenceMixin),
        ),
        migrations.CreateModel(
            name='HistoricalComptageSequence',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sequence_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ecart_with_previous', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical comptage sequence',
                'verbose_name_plural': 'historical comptage sequences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='ecartcomptage',
            name='ecart_positive_or_null',
        ),
        migrations.RemoveConstraint(
            model_name='ecartcomptage',
            name='result_positive_or_null',
        ),
        migrations.RemoveField(
            model_name='ecartcomptage',
            name='ecart',
        ),
        migrations.RemoveField(
            model_name='ecartcomptage',
            name='ligne_comptage_1',
        ),
        migrations.RemoveField(
            model_name='ecartcomptage',
            name='ligne_comptage_2',
        ),
        migrations.RemoveField(
            model_name='ecartcomptage',
            name='ligne_comptage_3',
        ),
        migrations.RemoveField(
            model_name='ecartcomptage',
            name='result',
        ),
        migrations.RemoveField(
            model_name='historicalecartcomptage',
            name='ecart',
        ),
        migrations.RemoveField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_1',
        ),
        migrations.RemoveField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_2',
        ),
        migrations.RemoveField(
            model_name='historicalecartcomptage',
            name='ligne_comptage_3',
        ),
        migrations.RemoveField(
            model_name='historicalecartcomptage',
            name='result',
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='final_result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='stopped_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='total_sequences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='final_result',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='stopped_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='total_sequences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comptagesequence',
            name='counting_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='comptagesequence',
            name='ecart_comptage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_sequences', to='inventory.ecartcomptage'),
        ),
        migrations.AddField(
            model_name='historicalcomptagesequence',
            name='counting_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail'),
        ),
        migrations.AddField(
            model_name='historicalcomptagesequence',
            name='ecart_comptage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ecartcomptage'),
        ),
        migrations.AddField(
            model_name='historicalcomptagesequence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comptagesequence',
            unique_together={('ecart_comptage', 'sequence_number')},
        ),
    ]
