# Generated by Django 5.2 on 2025-07-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_invetory_historicaljob_inventory_and_more'),
        ('inventory', '0006_fix_job_resource_references'),
    ]

    operations = [
    ]
