# Generated by Django 5.2 on 2025-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_fix_job_resource_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='affecte_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='entame_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
