# Generated by Django 5.2 on 2025-10-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_comptagesequence_historicalcomptagesequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countingdetail',
            name='job',
            field=models.ForeignKey(default=74, on_delete=django.db.models.deletion.CASCADE, to='inventory.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcountingdetail',
            name='job',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.job'),
        ),
    ]
