# Generated by Django 5.2 on 2025-10-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_countingdetail_job_historicalcountingdetail_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptagesequence',
            options={'ordering': ['ecart_comptage', 'sequence_number'], 'verbose_name': 'Séquence de comptage', 'verbose_name_plural': 'Séquences de comptage'},
        ),
        migrations.AlterModelOptions(
            name='ecartcomptage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Écart de comptage', 'verbose_name_plural': 'Écarts de comptage'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomptagesequence',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Séquence de comptage', 'verbose_name_plural': 'historical Séquences de comptage'},
        ),
        migrations.AlterModelOptions(
            name='historicalecartcomptage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Écart de comptage', 'verbose_name_plural': 'historical Écarts de comptage'},
        ),
        migrations.AddField(
            model_name='ecartcomptage',
            name='stopped_reason',
            field=models.CharField(blank=True, help_text='ECART_ZERO, RESOLU_MANUEL, etc.', max_length=100, null=True, verbose_name="Raison d'arrêt"),
        ),
        migrations.AddField(
            model_name='historicalecartcomptage',
            name='stopped_reason',
            field=models.CharField(blank=True, help_text='ECART_ZERO, RESOLU_MANUEL, etc.', max_length=100, null=True, verbose_name="Raison d'arrêt"),
        ),
        migrations.AlterField(
            model_name='comptagesequence',
            name='counting_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_sequences', to='inventory.countingdetail', verbose_name='Détail de comptage'),
        ),
        migrations.AlterField(
            model_name='comptagesequence',
            name='ecart_comptage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counting_sequences', to='inventory.ecartcomptage', verbose_name='Écart de comptage'),
        ),
        migrations.AlterField(
            model_name='comptagesequence',
            name='ecart_with_previous',
            field=models.IntegerField(blank=True, help_text='Différence avec la séquence précédente (N - N-1)', null=True, verbose_name='Écart avec le précédent'),
        ),
        migrations.AlterField(
            model_name='comptagesequence',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité comptée'),
        ),
        migrations.AlterField(
            model_name='comptagesequence',
            name='sequence_number',
            field=models.IntegerField(verbose_name='Numéro de séquence'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='final_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Résultat final'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecart_comptages', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Résolu'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='stopped_sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dernière séquence'),
        ),
        migrations.AlterField(
            model_name='ecartcomptage',
            name='total_sequences',
            field=models.IntegerField(default=0, verbose_name='Nombre total de séquences'),
        ),
        migrations.AlterField(
            model_name='historicalcomptagesequence',
            name='counting_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.countingdetail', verbose_name='Détail de comptage'),
        ),
        migrations.AlterField(
            model_name='historicalcomptagesequence',
            name='ecart_comptage',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.ecartcomptage', verbose_name='Écart de comptage'),
        ),
        migrations.AlterField(
            model_name='historicalcomptagesequence',
            name='ecart_with_previous',
            field=models.IntegerField(blank=True, help_text='Différence avec la séquence précédente (N - N-1)', null=True, verbose_name='Écart avec le précédent'),
        ),
        migrations.AlterField(
            model_name='historicalcomptagesequence',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité comptée'),
        ),
        migrations.AlterField(
            model_name='historicalcomptagesequence',
            name='sequence_number',
            field=models.IntegerField(verbose_name='Numéro de séquence'),
        ),
        migrations.AlterField(
            model_name='historicalecartcomptage',
            name='final_result',
            field=models.IntegerField(blank=True, null=True, verbose_name='Résultat final'),
        ),
        migrations.AlterField(
            model_name='historicalecartcomptage',
            name='justification',
            field=models.TextField(blank=True, null=True, verbose_name='Justification'),
        ),
        migrations.AlterField(
            model_name='historicalecartcomptage',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Résolu'),
        ),
        migrations.AlterField(
            model_name='historicalecartcomptage',
            name='stopped_sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dernière séquence'),
        ),
        migrations.AlterField(
            model_name='historicalecartcomptage',
            name='total_sequences',
            field=models.IntegerField(default=0, verbose_name='Nombre total de séquences'),
        ),
        migrations.AddIndex(
            model_name='comptagesequence',
            index=models.Index(fields=['ecart_comptage', 'sequence_number'], name='inventory_c_ecart_c_caa18d_idx'),
        ),
    ]
