# Generated by Django 5.2 on 2025-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_comptagesequence_options_and_more'),
        ('masterdata', '0003_alter_historicalproduct_barcode_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comptagesequence',
            new_name='comptage_seq_ecart_seq_idx',
            old_name='inventory_c_ecart_c_caa18d_idx',
        ),
        migrations.AddIndex(
            model_name='comptagesequence',
            index=models.Index(fields=['counting_detail'], name='comptage_seq_detail_idx'),
        ),
        migrations.AddIndex(
            model_name='comptagesequence',
            index=models.Index(fields=['counting_detail', 'ecart_comptage'], name='comptage_seq_detail_ecart_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['counting', 'location', 'product', 'job'], name='counting_detail_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['job'], name='counting_detail_job_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['counting'], name='counting_detail_counting_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['location'], name='counting_detail_location_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['product'], name='counting_detail_product_idx'),
        ),
        migrations.AddIndex(
            model_name='countingdetail',
            index=models.Index(fields=['last_synced_at'], name='counting_detail_synced_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartcomptage',
            index=models.Index(fields=['inventory'], name='ecart_inventory_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartcomptage',
            index=models.Index(fields=['resolved'], name='ecart_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='ecartcomptage',
            index=models.Index(fields=['inventory', 'resolved'], name='ecart_inventory_resolved_idx'),
        ),
        migrations.AddIndex(
            model_name='nserieinventory',
            index=models.Index(fields=['counting_detail'], name='nserie_counting_detail_idx'),
        ),
        migrations.AddIndex(
            model_name='nserieinventory',
            index=models.Index(fields=['counting_detail', 'n_serie'], name='nserie_detail_serie_idx'),
        ),
    ]
