# Generated by Django 5.2 on 2025-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_comptagesequence_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='reference',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
