# Generated by Django 5.2 on 2025-11-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_historicaljob_reference_alter_job_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='termine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='termine_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
