# Generated by Django 5.2 on 2025-12-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_assigment_termine_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE'), ('ANNULE', 'ANNULE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalassigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE'), ('ANNULE', 'ANNULE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicaljob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SAISIE MANUELLE', 'SAISIE MANUELLE'), ('ANNULE', 'ANNULE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicaljobdetail',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('TERMINE', 'TERMINE'), ('ANNULE', 'ANNULE')], default='EN ATTENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('VALIDE', 'VALIDE'), ('TERMINE', 'TERMINE'), ('SAISIE MANUELLE', 'SAISIE MANUELLE'), ('ANNULE', 'ANNULE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('TERMINE', 'TERMINE'), ('ANNULE', 'ANNULE')], default='EN ATTENTE', max_length=50),
        ),
    ]
