# Generated by Django 5.2 on 2025-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_assigment_annule_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaljob',
            old_name='termine_manuelle_date',
            new_name='termine_etat_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='termine_manuelle_date',
            new_name='termine_etat_date',
        ),
        migrations.RemoveField(
            model_name='historicaljob',
            name='termine_manuelle',
        ),
        migrations.RemoveField(
            model_name='job',
            name='termine_manuelle',
        ),
        migrations.AddField(
            model_name='assigment',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assigment',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='termine_etat',
            field=models.CharField(choices=[('automatique', 'AUTOMATIQUE'), ('manuelle', 'MANUELLE'), ('mixte', 'MIXE')], default='automatique', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljobdetail',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='termine_etat',
            field=models.CharField(choices=[('automatique', 'AUTOMATIQUE'), ('manuelle', 'MANUELLE'), ('mixte', 'MIXE')], default='automatique', max_length=50),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='termine_manuelle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='termine_manuelle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
