# Generated by Django 5.2 on 2025-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rename_termine_manuelle_date_historicaljob_termine_etat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonne',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personne',
            name='numero',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpersonne',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonne',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
