# Generated by Django 5.2 on 2025-12-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_ecartcomptage_manual_result_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpersonne',
            old_name='nom',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='nom',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='historicalpersonne',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
    ]
