# Generated by Django 5.2 on 2026-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_nom_historicalpersonne_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsetting',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('LANCEE', 'LANCEE'), ('CLOTURE', 'CLOTURE')], default='EN ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='status_date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsetting',
            name='status_date_lancement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('LANCEE', 'LANCEE'), ('CLOTURE', 'CLOTURE')], default='EN ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='setting',
            name='status_date_cloture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='status_date_lancement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
