# Generated by Django 5.2 on 2026-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_historicalsetting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='annule_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
