# Generated by Django 5.2 on 2026-02-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_historicalsetting_status_and_more'),
    ]

    # NOTE:
    # Cette migration tentait d'ajouter des colonnes déjà créées dans 0014.
    # Sur des bases où 0014 est déjà appliquée, cela provoque:
    # "la colonne annule_date ... existe déjà".
    # On la garde comme no-op pour préserver la chaîne de migrations
    # (0021 dépend de 0020) sans modifier le schéma.
    operations = []
