# Generated by Django 5.2 on 2026-02-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_add_missing_annule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigment',
            name='annule_date',
        ),
        migrations.RemoveField(
            model_name='historicalassigment',
            name='annule_date',
        ),
    ]
