# Generated by Django 5.2 on 2026-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_assigment_annule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='bloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigment',
            name='debloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='bloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='debloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE'), ('BLOQUE', 'BLOQUE'), ('DEBLOQUE', 'DEBLOQUE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalassigment',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'EN ATTENTE'), ('AFFECTE', 'AFFECTE'), ('PRET', 'PRET'), ('TRANSFERT', 'TRANSFERT'), ('ENTAME', 'ENTAME'), ('TERMINE', 'TERMINE'), ('BLOQUE', 'BLOQUE'), ('DEBLOQUE', 'DEBLOQUE')], max_length=10),
        ),
    ]
