# Generated by Django 5.2 on 2026-04-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_pdftask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='imprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assigment',
            name='imprime_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='imprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='imprime_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
