# Generated by Django 5.2 on 2026-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_assigment_bloqued_date_assigment_debloqued_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigment',
            name='bloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigment',
            name='debloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='bloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalassigment',
            name='debloqued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdftask',
            name='task_type',
            field=models.CharField(choices=[('inventory_jobs_pdf', 'PDF jobs inventaire'), ('job_assignment_pdf', 'PDF job/assignment')], max_length=50),
        ),
    ]
